import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '.././globals.css';
import SuperadminSidebar from '../components/ui/superadmin/sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: {
    template: `%s | ${process.env.APP_NAME}`,
    default: `${process.env.APP_NAME} Superadmin`,
  },
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
      <div className="flex h-screen bg-gray-100">
        <SuperadminSidebar />
        <div className="flex-1 flex flex-col">{children}</div>
      </div>
    </div>
  );
}
